pipeline:
  build_dev:
    image: java:openjdk-8
    secrets: [ application_dev ]
    commands:
    - whoami
    - echo -n "$APPLICATION_DEV" > src/main/resources/application-dev.properties
    - ls -l src/main/resources/application-dev.properties
    - ls -l gradlew
    - ls -l Dockerfile
    - chmod +x gradlew
    - ./gradlew clean build -x test
    when:
      branch: [ dev ]

  docker_dev:
    image: plugins/docker
    repo: lamth2/aikidodanang-backend
    secrets: [ docker_username, docker_password ]
    tags:
    - test
    when:
      branch: [ dev ]
