pipeline:
  build_dev:
    image: java:openjdk-8
    secrets: [ application_dev ]
    commands:
    - echo "$APPLICATION_DEV" >> src/main/resources/application.properties
    - chmod +x gradlew
    - ./gradlew clean build -x test
    when:
      branch: [ dev ]

  build_prod:
    image: java:openjdk-8
    secrets: [ application_prod ]
    commands:
    - echo "$APPLICATION_PROD" >> src/main/resources/application.properties
    - chmod +x gradlew
    - ./gradlew clean build -x test
    when:
      branch: [ master ]

  docker_dev:
    image: plugins/docker
    repo: lamth2/aikidodanang-backend
    secrets: [ docker_username, docker_password ]
    tags:
    - test
    when:
      branch: [ dev ]

  docker_prod:
    image: plugins/docker
    repo: lamth2/aikidodanang-backend
    secrets: [ docker_username, docker_password ]
    tags:
    - latest
    when:
      branch: [ master ]

  deploy_prod:
    image: appleboy/drone-ssh
    pull: true
    host: aikidodanang.org
    username: bfghfgg0205
    secrets: [ ssh_key ]
    port: 22
    script:
    - /opt/bin/docker-compose -f aikido-prod-compose.yaml pull
    - /opt/bin/docker-compose -f aikido-prod-compose.yaml up -d
    when:
      branch: [ master ]
  deploy_dev:
    image: appleboy/drone-ssh
    pull: true
    host: aikidodanang.org
    username: bfghfgg0205
    secrets: [ ssh_key ]
    port: 22
    script:
    - /opt/bin/docker-compose -f aikido-dev-compose.yaml pull
    - /opt/bin/docker-compose -f aikido-dev-compose.yaml up -d
    when:
      branch: [ dev ]

  notify_fail:
    image: drillster/drone-email
    from: drone@aikidodanang.org
    recipients: [ support@aikidodanang.org ]
    secrets: [ email_host, email_username, email_password ]
    subject: >
      [Build #{{build.number}} {{ build.status }}]
    body: |
      {{ repo.owner }}/{{ repo.name }} - branch {{commit.branch}}
      (Link: {{build.link}})
    when:
      status: [ failure ]

  notify_sucess:
    image: drillster/drone-email
    from: drone@aikidodanang.org
    recipients: [ support@aikidodanang.org ]
    secrets: [ email_host, email_username, email_password ]
    subject: >
      [Build #{{build.number}} {{ build.status }}]
    body: |
      {{ repo.owner }}/{{ repo.name }} - branch {{commit.branch}}
      (Link: {{build.link}})
    when:
      status: [ success ]