kind: pipeline
name: default

steps:
  - name: build_k8s
    image: gradle
    environment:
      APPLICATION_DEV:
        from_secret: application_dev
    commands:
      - gradle -g gradle
      - gradle clean build -x test
    when:
      branch: [ kubernetes ]

  - name: docker_k8s
    image: plugins/docker
    settings:
      repo: lamth2/aikidodanang-backend
      tags:
        - '${DRONE_COMMIT:0:8}'
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch: [ kubernetes ]

  - name: deploy_k8s
    image: vallard/drone-kube
    pull: true
    settings:
      template: k8s/app-k8s-dev.yml
      namespace: default
      token:
        from_secret: default_token
      ca:
        from_secret: default_ca
    when:
      branch: [ kubernetes ]

  - name: notify_fail
    image: drillster/drone-email
    settings:
      from: drone@aikidodanang.org
      recipients: [ support@aikidodanang.org ]
      host:
        from_secret: email_host
      username:
        from_secret: email_username
      password:
        from_secret: email_password
      subject: >
        [Build #{{build.number}} {{ build.status }}]
      body: |
        {{ repo.owner }}/{{ repo.name }} - branch {{commit.branch}}
        (Link: {{build.link}})
    when:
      status: [ failure ]

  - name: notify_sucess
    image: drillster/drone-email
    settings:
      from: drone@aikidodanang.org
      recipients: [ support@aikidodanang.org ]
      host:
        from_secret: email_host
      username:
        from_secret: email_username
      password:
        from_secret: email_password
      subject: >
        [Build #{{build.number}} {{ build.status }}]
      body: |
        {{ repo.owner }}/{{ repo.name }} - branch {{commit.branch}}
        (Link: {{build.link}})
    when:
      status: [ success ]
