pipeline:
  build_dev:
    image: java:openjdk-8
    secrets: [ application_dev ]
    commands:
    - echo "$APPLICATION_DEV" >> src/main/resources/application.properties
    - chmod +x gradlew
    - ./gradlew clean build -x test
    when:
      branch: [ dev ]

  build_prod:
    image: java:openjdk-8
    secrets: [ application_prod ]
    commands:
    - echo "$APPLICATION_PROD" >> src/main/resources/application.properties
    - chmod +x gradlew
    - ./gradlew clean build -x test
    when:
      branch: [ master ]

  docker_dev:
    image: plugins/docker
    repo: lamth2/aikidodanang-backend
    secrets: [ docker_username, docker_password ]
    tags:
    - test
    when:
      branch: [ dev ]

  docker_prod:
    image: plugins/docker
    repo: lamth2/aikidodanang-backend
    secrets: [ docker_username, docker_password ]
    tags:
    - latest
    when:
      branch: [ master ]

  deploy_dev:
    image: appleboy/drone-ssh
    host: 35.226.108.125
    secrets: [ ssh_key ]
    port: 22
    script:
    - echo hello
    - echo world
