pipeline:
  build:
    image: java:openjdk-8
    commands:
      - chmod +x gradlew
      - ./gradlew clean build
  docker:
    image: plugins/docker
    repo: lamth2/aikidodanang-backend
    registry: hub.docker.com
    secrets: [ docker_username, docker_password ]
