pipeline:
  build:
    image: java:openjdk-8
    commands:
      - chmod +x gradlew
      - ./gradlew clean build
  docker:
    image: plugins/docker
    secrets: [ docker_hub_user, docker_hub_password ]
    repo: lamth2/aikidodanang-backend
    tags: latest
  deploy:
    image: appleboy/drone-ssh
    host: 35.226.108.125
    secrets: [ ssh_key ]
    commands:
    - docker-compose -f aikido-container-only.yaml up -d
