pipeline:
  build:
    image: java:openjdk-8
    commands:
      - chmod +x gradlew
      - ./gradlew clean build
  docker:
    image: plugins/docker
    debug: true
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    repo: lamth2/aikidodanang-backend
    tags:
      - latest

