kind: pipeline
name: default

steps:
  - name: build_dev
    image: java:openjdk-8
    environment:
      APPLICATION_DEV:
        from_secret: application_dev
    commands:
    - echo "$APPLICATION_DEV" >> src/main/resources/application.properties
    - chmod +x gradlew
    - ./gradlew clean build -x test
    when:
      branch: [ dev ]

  - name: build_prod
    image: java:openjdk-8
    environment:
      APPLICATION_PROD:
        from_secret: application_prod
    commands:
    - echo "$APPLICATION_PROD" >> src/main/resources/application.properties
    - chmod +x gradlew
    - ./gradlew clean build -x test
    when:
      branch: [ master ]

  - name: docker_dev
    image: plugins/docker
    settings:
      repo: lamth2/aikidodanang-backend
      tags:
        - '${DRONE_COMMIT:0:8}'
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch: [ dev ]

  - name: docker_prod
    image: plugins/docker
    settings:
      repo: lamth2/aikidodanang-backend
      tags:
      - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch: [ master ]

  - name: build_k8s
    image: java:openjdk-8
    environment:
      APPLICATION_K8S:
        from_secret: application_k8s
    commands:
      - echo "$APPLICATION_K8S" >> src/main/resources/application.properties
      - chmod +x gradlew
      - ./gradlew clean build -x test
    when:
      branch: [ kubernetes ]

  - name: docker_k8s
    image: plugins/docker
    settings:
      repo: lamth2/aikidodanang-backend
      tags:
        - '${DRONE_COMMIT:0:8}'
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch: [ kubernetes ]

  - name: deploy_k8s
    image: vallard/drone-kube
    pull: true
    settings:
      template: k8s/app-k8s-dev.yml
      namespace: default
      token:
        from_secret: default_token
      ca:
        from_secret: default_ca
    when:
      branch: [ kubernetes ]

  - name: deploy_dev
    image: appleboy/drone-ssh
    pull: true
    settings:
      host: aikidodanang.org
      username: bfghfgg0205
      key:
        from_secret: ssh_key
      port: 22
      script:
        - /opt/bin/docker-compose -f aikido-dev-compose.yaml pull
        - /opt/bin/docker-compose -f aikido-dev-compose.yaml up -d
    when:
      branch: [ dev ]

  - name: notify_fail
    image: drillster/drone-email
    settings:
      from: drone@aikidodanang.org
      recipients: [ support@aikidodanang.org ]
      host:
        from_secret: email_host
      username:
        from_secret: email_username
      password:
        from_secret: email_password
      subject: >
        [Build #{{build.number}} {{ build.status }}]
      body: |
        {{ repo.owner }}/{{ repo.name }} - branch {{commit.branch}}
        (Link: {{build.link}})
    when:
      status: [ failure ]

  - name: notify_sucess
    image: drillster/drone-email
    settings:
      from: drone@aikidodanang.org
      recipients: [ support@aikidodanang.org ]
      host:
        from_secret: email_host
      username:
        from_secret: email_username
      password:
        from_secret: email_password
      subject: >
        [Build #{{build.number}} {{ build.status }}]
      body: |
        {{ repo.owner }}/{{ repo.name }} - branch {{commit.branch}}
        (Link: {{build.link}})
    when:
      status: [ success ]
