kind: pipeline
name: default

steps:
  - name: prepare_k8s
    image: bash
    environment:
      APPLICATION_DEV:
        from_secret: application_dev
    commands:
      - echo "$APPLICATION_DEV" >> src/main/resources/application.properties
      - chmod 777 -R $(pwd)
    when:
      branch: [ kubernetes ]

  - name: build_k8s
    image: gradle
    commands:
      - gradle build -x test
    when:
      branch: [ kubernetes ]

  - name: docker_k8s
    image: plugins/docker
    settings:
      repo: lamth2/aikidodanang-backend
      tags:
        - '${DRONE_COMMIT:0:8}'
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch: [ kubernetes ]

  - name: deploy_k8s
    image: ethicaljobs/drone-gce-deploy
    pull: true
    environment:
      TAG: '${DRONE_COMMIT:0:8}'
    settings:
      cluster: aikido-cluster
      zone: asia-southeast1-a
      artefacts: k8s/app-k8s-dev.yml
      gce_key:
        from_secret: gce_token
    when:
      branch: [ kubernetes ]
#
#  - name: notify_fail
#    image: drillster/drone-email
#    settings:
#      from: drone@aikidodanang.org
#      recipients: [ support@aikidodanang.org ]
#      host:
#        from_secret: email_host
#      username:
#        from_secret: email_username
#      password:
#        from_secret: email_password
#      subject: >
#        [Build #{{build.number}} {{ build.status }}]
#      body: |
#        {{ repo.owner }}/{{ repo.name }} - branch {{commit.branch}}
#        (Link: {{build.link}})
#    when:
#      status: [ failure ]
#
#  - name: notify_sucess
#    image: drillster/drone-email
#    settings:
#      from: drone@aikidodanang.org
#      recipients: [ support@aikidodanang.org ]
#      host:
#        from_secret: email_host
#      username:
#        from_secret: email_username
#      password:
#        from_secret: email_password
#      subject: >
#        [Build #{{build.number}} {{ build.status }}]
#      body: |
#        {{ repo.owner }}/{{ repo.name }} - branch {{commit.branch}}
#        (Link: {{build.link}})
#    when:
#      status: [ success ]
