pipeline:
  build:
    image: library/maven:3-jdk-8
    secrets: [ application_prod ]
    commands:
    - echo -n "$APPLICATION_PROD" > src/main/resources/application-template.properties
    - mvn clean install
  docker:
    image: plugins/docker
    repo: lamth2/aikidodanang-backend
    secrets: [ docker_username, docker_password ]
    tags:
    - test
