pipeline:
  build:
    image: java:openjdk-8
    commands:
      - chmod +x gradlew
      - ./gradlew clean build
  docker:
    image: plugins/docker
    debug: true
    secrets: [ docker_username, docker_password ]
    repo: lamth2
    tags:
      - aikidodanang-backend

