pipeline:
  build:
    image: java:openjdk-8
    commands:
      - chmod +x gradlew
      - ./gradlew clean build
  docker:
    image: plugins/docker
    debug: true
    commands:
      - echo $DOCKER_USERNAME
      - echo $DOCKER_PASSWORD
    secrets: [ docker_username, docker_password ]
    repo: lamth2/aikidodanang-backend
    tags:
      - latest

