pipeline:
  build:
    image: java:openjdk-8
    commands:
      - chmod +x gradlew
      - ./gradlew clean build
  docker:
    image: plugins/docker
    secrets: [ docker_hub_user, docker_hub_password ]
    repo: lamth2/aikidodanang-backend
    registry: hub.docker.com
    tags: latest

