---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aikido-k8s-dev
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aikido-k8s-dev
        k8s-app: aikido-k8s-dev
    spec:
      containers:
        - image: lamth2/aikidodanang-backend:{{=template.environment.TAG}}
          name: aikido-k8s-dev
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: aikido-k8s-dev
  name: aikido-k8s-dev
  namespace: dev
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: web
  selector:
    k8s-app: aikido-k8s-dev
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aikido-k8s-dev
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: dev.lamth.info
      http:
        paths:
          - path: /
            backend:
              serviceName: aikido-k8s-dev
              servicePort: web
